export type PrintOptions = {
  primary?: string
  accent?: string
}

export function printHtml(title: string, html: string, opts: PrintOptions = {}) {
  const w = window.open('', '_blank', 'width=1024,height=768')
  if (!w) return
  const primary = opts.primary || '#3B82F6' // blue-500
  const accent = opts.accent || '#10B981' // emerald-500
  w.document.open()
  w.document.write(`<!doctype html><html><head><meta charset="utf-8"/><title>${title}</title><style>
    :root { --primary: ${primary}; --accent: ${accent}; --ink:#111827; --muted:#6b7280; }
    *{box-sizing:border-box}
    body{font-family:system-ui,Segoe UI,Roboto,Helvetica,Arial,sans-serif;margin:0;color:var(--ink);-webkit-print-color-adjust:exact;print-color-adjust:exact}
    .container{padding:28px}
    .header{display:flex;justify-content:space-between;align-items:center;margin-bottom:16px}
    .brand{display:flex;align-items:center;gap:10px}
    .badge{background:var(--accent);color:white;font-weight:600;border-radius:999px;padding:2px 10px;font-size:12px}
    h1{margin:0 0 4px;font-size:22px}
    h2{margin:14px 0 8px;font-size:14px;color:var(--muted)}
    .card{border:1px solid #e5e7eb;border-radius:10px;overflow:hidden;margin-bottom:14px}
    .card-title{background:var(--primary);color:white;font-weight:600;padding:8px 12px}
    table{border-collapse:collapse;width:100%}
    thead th{background:var(--primary);color:white;text-align:left;font-weight:600;padding:10px 8px;border-right:1px solid rgba(255,255,255,.25)}
    thead th:last-child{border-right:none}
    tbody td{border-top:1px solid #e5e7eb;padding:8px}
    tbody tr:nth-child(even){background: color-mix(in oklab, var(--accent) 10%, #ffffff)}
    .num{text-align:right}
    .muted{color:var(--muted)}
    footer{margin-top:16px;color:var(--muted);font-size:12px;text-align:center}
    @page { margin: 16mm }
  </style></head><body><div class="container">${html}<footer>Generated by Finance Tracker</footer></div></body></html>`)
  w.document.close()
  w.focus()
  setTimeout(() => w.print(), 300)
}
